# Site settings
title: "Pino Volpe, web designer, front-end web developer, WordPress developer"
description: "Progettazione e realizzazione completa di siti web responsive. Grafica, HTML, CSS, JavaScript e WordPress. Social media marketing e gestione profili sui social network."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Pino Volpe"
resume_title:                   "web designer, front-end web developer, WordPress developer"
resume_contact_email:           "pino.volpe@gmail.com"
resume_contact_telephone:       "+39 347 04.34.364"
resume_contact_address:         "Venezia, Italia"
resume_header_contact_info: "Venezia, Italia | +39 347 04.34.364 | pino.volpe@gmail.com"
resume_header_intro: "<p>Pino Volpe, nato a Napoli nel 1980. Diplomato in <strong>grafica</strong> e <strong>web design</strong> presso l'Istituto LGD (Laboratorio di Grafica e Design) di Napoli. Dal 2006 vivo a Venezia, dove svolgo la funzione di <strong>web designer</strong>, <strong>front-end web developer</strong> e <strong>creazione e sviluppo di temi e plugin WordPress</strong>.</p><p>Ho una solida esperienza nella <strong>realizzazione di siti web</strong> conformi ai W3C Standards, con una particolare attenzione rivolta ai principi di usabilità, accessibilità e <strong>ottimizzazione per i motori di ricerca</strong>. Le mie competenze tecniche vanno dalla grafica ai linguaggi <strong>XHTML</strong>, <strong>HTML5</strong> e <strong>CSS3</strong>; dal <strong>SEO/SEM Management</strong> e <strong>Web Analitycs</strong> alle tematiche di <strong>UI/UX Design</strong>; dall'uso di CMS <strong>WordPress</strong> all'utilizzo di librerie <strong>JavaScript</strong> e <strong>jQuery</strong>. Nella progettazione delle interfacce seguo le regole del <strong>design responsivo</strong> con approccio UCD (<strong>User-centered design</strong>, progettazione centrata sull'utente).</p><p>Posseggo una cultura di buon livello ed una spiccata curiosità che mi porta a tenermi costantemente aggiornato su tutte le novità che riguardano la mia professione. Ho un forte interesse per la <strong>comunicazione pubblicitaria</strong>, i <strong>social media</strong>, la <strong>fotografia</strong>, lo sport e i viaggi. Completano il profilo: una buona conoscenza di <strong>Inglese e Spagnolo</strong>, sia parlato che scritto, ottima capacità di analisi, approccio pratico, <strong>propensione a lavorare in team</strong>, rapidità di apprendimento e capacità di gestione di più progetti simultaneamente.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_skills:          true
# resume_section_projects:        true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_website_url:           "https://www.pinovolpe.com/"
  resume_github_url:            "https://github.com/pinovolpe"
  resume_linkedin_url:          "https://www.linkedin.com/in/pinovolpe"
  resume_facebook_url:          "https://www.facebook.com/pinovolpe"
  resume_instagram_url:         "http://instagram.com/pinovolpe"
  resume_twitter_url:           "http://twitter.com/pinovolpe"
  # resume_dribbble_url:          "https://dribbble.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
